name: CI

on:
  push:
    branches:
      - master
      - 'v*' # older version branches
    tags:
      - '*'
  pull_request:
  schedule:
    - cron:  '0 3 * * *' # daily at 3am

jobs:
  test:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      run: yarn install

    - name: lint
      run: yarn lint

    - name: test
      run: yarn test
      env:
        CI: true
